### ISSUE TITLE
I would like some feedback

### ISSUE THREAD

**Issue by JonatanSalas** [k0shk0sh/Android-MVP-for-dummies#1]
Hey, recently I saw your code (really nice and simple), and it behaves the same as a library that about 3 weeks I have made open source -> https://github.com/BlackBoxVision/mvp-helpers. 

Would you like to give me some feedback about it? It has another differences from your code, but the main remains the same.

Anyway thanks for your time to read this issue! 😄

**Comment by k0shk0sh** [comment]
Hello Jonathan, thanks for seeking my feedback, currently I'm using ThirtyInch library which provides state restoration & RxJava support plus some handy methods to send stuff to view after view is attached. I see that you are using butterknife in your library & providing devs with extra step to include your library, my suggestion would be to remove that dependency and let devs decide to either include butterknife by themselves or use alternative. 
Thanks

**Comment by JonatanSalas** [comment]
@k0shk0sh Thank you very much for your feedback! 

Yes, it seems that if I don't enforce devs to use a lib they don't want to, it will gain a little bit more adoption. I don't know about ThirtyInch library. I will take a look at it!
